feat: button template
esc-chula/gearfest-frontend pull request #8
Opened 2024-01-11 16:48 UTC by mildrrnt

## Change made

- [x] Bug fixes
- [x] New features
- [ ] Breaking changes

## Describe what you have done

- Implement reusable button components (with and without scores) to use inside story.
- Implement reusable card components with customizable child.
- Fix score increment logic.

### New Features

- Buttons and question card template.

### Fix

- I noticed "null" value when adding scores into Local Storage. It is fixed by changing the beginning dictionary index to 0 instead of 1 in `store/score.ts`

2024-01-12 03:58 UTC, shalluv requested changes

2024-01-12 03:58 UTC, shalluv commented on src/components/story/Button.tsx
> +  redirect: string;
I think it would be better if we used `handleClick` as props, as it would provide more flexibility for the button.

2024-01-12 03:58 UTC, shalluv commented on src/components/story/ฺButtonScore.tsx
please remove special character from filename

2024-01-12 03:58 UTC, shalluv commented on src/components/story/ฺButtonScore.tsx
This is similar to `Button.tsx`, just serve different functions, correct?

According to

> I think it would be better if we used `handleClick` as props, as it would provide more flexibility for the button.

We could simply `import Button from Button.tsx`

Then use it as follows `return <Button text={text} handleClick={handleClick} />`

2024-01-12 03:58 UTC, shalluv commented on src/components/story/Tap.tsx
I believe using `<a href={redirect} ...>` would better serve the purpose of redirection.

2024-01-14 19:34 UTC, mildrrnt commented on src/components/story/ฺButtonScore.tsx
Yes, I see what you mean!

I have some questions about it though. According to [Astro Docs about Dynamic Attribute](https://docs.astro.build/en/core-concepts/astro-syntax/), do you have any approaches other than using a client-side script to add the event handler like it is said in the document?

Currently, I tried to do this:
In Button.tsx

```
interface Props {
  text: string;
  handleClick: () => void;
}
```

and in 1.astro
```
const handleClick = () => {
  console.log('This is running')
  location.href = "./2";
};
---
<Button client:load text="Option 1" handleClick={() => {handleClick}} />
```
But it doesn't quite work TT.

2024-01-15 07:10 UTC, mildrrnt commented on src/components/story/ฺButtonScore.tsx
I tried this and it seems to work, but if you have any suggestion/better practice please let me know na kub. 🙇 

---
### Button.tsx
This component will be used in both scored and unscored button.

```
interface Props {
  text: string;
  id: string;
}

const Button = ({ text, id }: Props) => {
  return (
    <button
      className="flex h-fit w-full flex-wrap items-center justify-center rounded-xl bg-mutedpurple px-4 py-3.5 text-center text-xs font-normal text-white"
      id={id}    
    >
      {text}
    </button>
  );
};

export default Button;
```

### 1.astro (Unscored)
Add event listener to all buttons.
```
<script>
  let buttonArray = document.querySelectorAll("button");
  buttonArray.forEach(function(btn) {
    btn.addEventListener("click", function() {
      location.href = "./2";
    });
}); 
</script>
```

### 2.astro (Scored) 

```
<script>
  import { addScores } from "../../store/score.ts";
  const handleClick = (scoreArray: Array<number>) => {
    addScores(scoreArray);
    location.href = "./3";
  }
  document.getElementById("1").addEventListener("click",function() {handleClick([1,2,0,1,0])})
  document.getElementById("2").addEventListener("click",function() {handleClick([2,0,2,0,1])})
  document.getElementById("3").addEventListener("click",function() {handleClick([0,1,1,2,1])})
</script>
```

2024-01-16 14:26 UTC, shalluv commented on src/components/story/ฺButtonScore.tsx
I believe the good approach would be to create two additional React components that utilize `Button.tsx`.

2024-01-16 14:30 UTC, shalluv commented on src/components/story/ฺButtonScore.tsx
Alternatively, we could create an additional component for scoring. For the link button, we could utilize `<a href="">` within `.astro` files.

2024-01-22 10:38 UTC, shalluv approved these changes
LGTM

2024-01-22 10:39 UTC, merged